### ISSUE TITLE
tv example panics immmediately

### ISSUE THREAD

**Issue by scottjg** [brutella/hc#142]
```
panic: adding a linked should be done after the server was added to an accessory

goroutine 1 [running]:
github.com/brutella/hc/service.(*Service).AddLinkedService(...)
	/Users/scottjg/work/hc/service/service.go:96
main.addInputSource(0xc0000b8bc0, 0x1, 0x13f45f6, 0x6, 0x3)
	/Users/scottjg/work/hc/_example/tv/main.go:23 +0x65c
main.main()
	/Users/scottjg/work/hc/_example/tv/main.go:139 +0x423
```

was there an api update that didn't make it in the example? or is it maybe something wrong with my environment?

**Comment by brutella** [comment]
Fixed by b7c9de178b3f6e48ffc8cee40c6cb294cfca357b
